user = input('Digite algo:')
print('O tipo primitivo deste valor é:', type(user))
print('Só tem espaços?', user.isspace())
print('É um número?', user.isnumeric())
print('É alfabético?', user.isalpha())
print('É alfanumérico?', user.isalnum())
print('Está em maiúsculas?', user.isupper())
print('Está em minúsculas?', user.islower())
print('Está capititalizado?', user.istitle())
